package com.memorylens.app.inference

import android.util.Log
import com.memorylens.app.utils.LatencyTracker

/**
 * Cue generator for the pipeline.
 *
 * CURRENT MODE — Template only (hackathon MVP on MediaTek A34).
 * [generate] builds a warm, natural sentence from name, relationship, and the most
 * recent conversation summary.  Latency is measured so the dashboard row updates
 * correctly (it will show < 1 ms in template mode).
 *
 * The LLM latency row in the dashboard reads "Template mode" when [llmAvailable]
 * is false, making it clear to testers that neural generation is disabled.
 *
 * Stage: [LatencyTracker.STAGE_LLM_GENERATION]
 *
 * ---------------------------------------------------------------------------
 * TODO (Hackathon – S25 Ultra): Re-enable ExecuTorch Llama 3.2 1B inference.
 * Steps:
 *   1. Place llama3_2_1b_instruct.pte in assets/models/
 *   2. Add ExecuTorch AAR to app/libs/ and uncomment fileTree in build.gradle
 *   3. Replace the template body of [generate] with [runLlmGeneration]
 *   4. Call [initLlm] from [init]
 * ---------------------------------------------------------------------------
 */
class LlmRunner {

    private val TAG = "LlmRunner"

    /** Always false until ExecuTorch Llama is integrated at the hackathon. */
    val llmAvailable: Boolean = false

    /** No-op initialisation in template mode.  Reserved for ExecuTorch setup. */
    suspend fun init() {
        Log.i(TAG, "LlmRunner in template mode — no ExecuTorch model loaded")
        // TODO: call initLlm() here when Llama .pte is present
    }

    /**
     * Generate a memory cue for the identified person.
     * In template mode this is instant (<1 ms).  Returns Pair<cue text, token count>.
     * Token count is 0 in template mode; it will reflect real token counts once the
     * neural runner is enabled.
     * [stage: llm_generation]
     */
    fun generate(name: String, relationship: String, summaries: List<String>): Pair<String, Int> {
        LatencyTracker.markStart(LatencyTracker.STAGE_LLM_GENERATION)
        val cue = buildTemplateCue(name, relationship, summaries)
        LatencyTracker.markEnd(LatencyTracker.STAGE_LLM_GENERATION)
        Log.d(TAG, "Generated cue (template): $cue")
        return Pair(cue, 0)
    }

    /**
     * Warm, context-aware template sentence.
     * Only uses a summary as context if it was typed by the user — auto-generated
     * presence-log entries ("X was present on ... for Y seconds.") are skipped
     * because they add no useful memory context to the spoken cue.
     */
    private fun buildTemplateCue(name: String, relationship: String, summaries: List<String>): String {
        val meaningful = summaries.firstOrNull { s ->
            s.isNotBlank() && !isAutoGenerated(s)
        }
        return if (meaningful != null) {
            "This is $name, your $relationship. $meaningful"
        } else {
            "This is $name, your $relationship."
        }
    }

    /** Returns true for the fallback presence-log format saved when user presses Skip. */
    private fun isAutoGenerated(summary: String): Boolean =
        summary.contains("was present on") && summary.trimEnd().endsWith("seconds.")

    fun close() {
        // Nothing to release in template mode
        // TODO: release ExecuTorch LLM module here when enabled
    }

    // ---------------------------------------------------------------------------
    // TODO (Hackathon – S25 Ultra): ExecuTorch Llama 3.2 1B runner
    //
    // private val PTE_MODEL = "models/llama3_2_1b_instruct.pte"
    // private val MAX_NEW_TOKENS = 60
    // private val TEMPERATURE = 0.3f
    // private val TIMEOUT_MS = 5_000L
    // private val STOP_TOKENS = setOf("\n\n", "<|eot_id|>")
    // private var llmModule: Any? = null   // com.facebook.executorch.LlmModule
    //
    // private suspend fun initLlm() = withContext(Dispatchers.IO) {
    //     val cacheFile = context.cacheDir.resolve("llama3_2_1b.pte")
    //     if (!cacheFile.exists()) {
    //         context.assets.open(PTE_MODEL).use { ins ->
    //             cacheFile.outputStream().use { out -> ins.copyTo(out) }
    //         }
    //     }
    //     val cls = Class.forName("com.facebook.executorch.LlmModule")
    //     llmModule = cls.getConstructor(String::class.java, String::class.java)
    //         .newInstance(cacheFile.absolutePath, "")
    //     Log.i(TAG, "LLM loaded via ExecuTorch")
    // }
    //
    // private fun buildPrompt(name: String, relationship: String, summaries: List<String>): String {
    //     val ctx = summaries.mapIndexed { i, s -> "${i+1}. $s" }.joinToString("\n")
    //     return """<|begin_of_text|><|start_header_id|>system<|end_header_id|>
    // You are a private memory assistant. Generate a single short, warm, natural sentence
    // to help someone remember the person in front of them. Be concise. Max 2 sentences.
    // Never mention Alzheimer's or memory loss.
    // <|eot_id|><|start_header_id|>user<|end_header_id|>
    // Person: $name
    // Relationship: $relationship
    // Recent context:
    // $ctx
    // Generate the memory cue now:
    // <|eot_id|><|start_header_id|>assistant<|end_header_id|>"""
    // }
    //
    // private fun runLlmGeneration(name, relationship, summaries): Pair<String, Int> {
    //     val prompt = buildPrompt(name, relationship, summaries)
    //     val sb = StringBuilder(); var count = 0
    //     // ... ExecuTorch generate() via reflection ...
    //     return Pair(sb.toString().trim(), count)
    // }
    // ---------------------------------------------------------------------------
}
